### ISSUE TITLE
http links on https pages

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/slashcode#408]
Have unconfirmed reports of http links showing up on https pages.

**Comment by paulej72** [comment]
yep that is a problem. links are hard coded all over the site.  should use a different method to generate them that is protocol agnostic.  there are two vars that reference the root of a site and one is http and one is https.

**Comment by NCommander** [comment]
Shouldn't be an issue, as we're going HTTPS by default next upgrade; absolutedir and absolutedir_secure == https. Given no one is using slashcode/rehash except us, I don't think its worth the headache to try and fix this "properly", so I'm killing this bug, as it will be fixed in the next site upgrade.
